#ifndef DEFINE_H
#define DEFINE_H

/*
 * Auto-generated by YOLO Studio Board App Generator
 * Model configuration for Renesas RZ/V2N DRP-AI
 */

/* Model configuration */
#define MODEL_NAME      "YOLOv8 (ultralytics 8.4.7)"
#define MODEL_DIR       "sub_0000__CPU_DRP_TVM"
#define NUM_CLASSES     1
#define INPUT_W         640
#define INPUT_H         640
#define INPUT_C         3
#define NUM_ANCHORS     8400

/*
 * Output format:
 *   0 = "decoded"   — single tensor [1, 4+NC, num_anchors] (cx, cy, w, h, cls...)
 *   1 = "cut_heads" — 6 tensors: 3x cv2 [1,64,H,W] + 3x cv3 [1,NC,H,W] (DFL raw)
 *
 * Cut heads require DFL (Distribution Focal Loss) decoding on CPU.
 * This is the standard Renesas-recommended export format for YOLOv8/YOLO11.
 */
#define OUTPUT_FORMAT   1
#define NUM_OUTPUTS     6
#define DFL_REG_MAX     16

/* Detection thresholds */
#define CONF_THRESHOLD  0.80f
#define NMS_THRESHOLD   0.80f
#define MAX_DETECTIONS  1

/* Camera settings */
#define CAMERA_DEVICE   "/dev/video0"
#define CAMERA_W        640
#define CAMERA_H        480

/* Display mode: 0=console, 1=wayland */
#define DISPLAY_MODE    1

/* DRP-AI device */
#define DRPAI_DEV       "/dev/drpai0"

/*
 * DRP-AI frequency settings (RZ/V2N)
 *
 *   DRP_MAX_FREQ: DRP core frequency
 *     2=420MHz, 3=315MHz, 4=252MHz, 5=210MHz, 127=9.8MHz(min)
 *
 *   DRPAI_FREQ: AI-MAC frequency
 *     1=1GHz, 2=1GHz, 3=630MHz, 4=420MHz, 5=315MHz, 127=10MHz(min)
 */
#define DRP_MAX_FREQ    2
#define DRPAI_FREQ      1

/* Class names */
static const char* CLASS_NAMES[] = { "bowling-pins" };

/* Display text rendering */
#define BOX_LINE_SIZE       2
#define CHAR_SCALE_LARGE    0.8f
#define CHAR_SCALE_SMALL    0.7f
#define CHAR_THICKNESS      2
#define LINE_HEIGHT_PX      30

/* Thread polling interval (microseconds) — used by multi-threaded camera pipeline */
#define WAIT_TIME           1000

#endif /* DEFINE_H */
